name = "FASolverAvalanche"
uuid = "d94f865e-9be7-4415-9b4a-0e34ca8c7922"
authors = ["Tanish Jain"]
version = "1.0.0-DEV"

[deps]
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
